### ISSUE TITLE
Copy Right year needs to be updated to 2020.

### ISSUE THREAD

**Issue by KashyapNPS** [statisticsnorway/klass-subsets-client#113]
Copy Right year needs to be updated to 2020.

**To Reproduce**
1. Go to https://subsets-client.staging-bip-app.ssb.no/
2. Scroll down to the bottom of the page
4. Copy Right year shows 2019

**Expected behavior**
1. Copy Right year is updated to 2020

**Screenshots**
Please find the attached screen shot
<img width="184" alt="Screenshot 2020-05-12 at 13 18 38" src="https://user-images.githubusercontent.com/46371482/81680271-3031fc00-9453-11ea-9ec0-146f0346b44e.png">

**Desktop (please complete the following information):**
-   Device: Web
-   OS:  MacOs Catalina 10.15.4 
-   Browser Google Chrome
-   Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by alina-lapina** [comment]
fixed in v0.3.1
