### ISSUE TITLE
Internal server error on trying to publish version 2 for the given uttrekk.

### ISSUE THREAD

**Issue by KashyapNPS** [statisticsnorway/klass-subsets-client#146]
**Describe the bug**
Internal server error on trying to publish version 2 for the uttrekk.

**App version**
V0.4.4

**To Reproduce**
1. Create an uttrekk 
In this case:
ID: uttrekk_for_test_001_12_aug_2020
Versjon: 1
Gyldighetsperiode: 2020-01-01.
Versjon 01 fra 01/01/2020 til dd/mm/yyyy
Ansvarlig seksjon: 320 - Seksjon for befolkningsstatistikk
Emneområde: Befolkning

2. Now add a new version to this uttrekk
ID: uttrekk_for_test_001_12_aug_2020
Versjon: 2
Gyldighetsperiode: 2000-01-01.
Versjon 01 fra 01/01/2020 til dd/mm/yyyy
Ansvarlig seksjon: 320 - Seksjon for befolkningsstatistikk
Emneområde: Befolkning
3. Try to Publish this uttrekk.
4. See error Internal Server Error 400 Bad Request: [Schema validation error: [#/codes/0: required key [urn] not found, #/codes/1: required key [urn] not found, #/administrativeDetails/1/values/1: expected type: String, found: Null, #/administrativeDetails/1/values/2: expected type: String, found: Null]]

**Expected behavior**
User is able to publish the corresponding version of uttrekk.

**Screenshots**
<img width="1595" alt="Screenshot 2020-08-12 at 14 11 07" src="https://user-images.githubusercontent.com/46371482/90021820-0b4b6000-dcb2-11ea-8bb7-548219ede0aa.png">

**Dependencies**
Are there other issues to be resolved first?

**Desktop (please complete the following information):**
OS: MacOS Catalina 10.15.4
Browser Chrome
Version 83.0.4103.61 (Official Build) (64-bit)

**JSON:**
{
    "id": "uttrekk_for_test_001_12_aug_2020",
    "name": [
        {
            "languageCode": "nb",
            "languageText": "Uttrekk for test 001 12 Aug 2020"
        }
    ],
    "shortName": "",
    "administrativeStatus": "INTERNAL",
    "validFrom": "2000-01-01T00:00:00.000Z",
    "validUntil": null,
    "createdBy": "320 - Seksjon for befolkningsstatistikk ",
    "administrativeDetails": [
        {
            "administrativeDetailType": "ANNOTATION",
            "values": [
                "Befolkning"
            ]
        },
        {
            "administrativeDetailType": "ORIGIN",
            "values": [
                "urn:ssb:klass-api:classifications:6",
                null,
                null
            ]
        }
    ],
    "description": [
        {
            "languageCode": "nb",
            "languageText": "Versjon 01 fra 01/01/2020 til dd/mm/yyyy"
        }
    ],
    "version": "2",
    "versionRationale": [
        {
            "languageText": "Versjon 02 fra 01/01/2000 til 01/01/2010",
            "languageCode": "nb"
        }
    ],
    "versionValidFrom": "2000-01-01T00:00:00.000Z",
    "versionValidUntil": "2010-01-01T00:00:00.000Z",
    "codes": [
        {
            "parentCode": "01",
            "level": "3",
            "name": "Dyrking av ettårige vekster",
            "shortName": "Dyrking av ettårige vekster",
            "presentationName": "",
            "validFromInRequestedRange": "2010-01-01",
            "validToInRequestedRange": null,
            "_links": {
                "self": {}
            },
            "rank": 1
        },
        {
            "parentCode": "A",
            "level": "2",
            "name": "Jordbruk og tjenester tilknyttet jordbruk, jakt og viltstell",
            "shortName": "Jordbruk, tilhør. tjenester, jakt",
            "presentationName": "",
            "validFromInRequestedRange": "2010-01-01",
            "validToInRequestedRange": null,
            "_links": {
                "self": {}
            },
            "rank": 2
        }
    ],
    "createdDate": "2020-08-12T12:08:09Z",
    "lastUpdatedDate": "2020-08-12T12:08:09Z",
    "_links": {}
}

**Comment by alina-lapina** [comment]
Outdated
