### ISSUE TITLE
Irrelevant "Sending version" message on metadata saving

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#211]
**Describe the bug**
When metadata is failing to be saved for a new subset, the "Sending version data to the server" message still shown.

**App version**
v0.6.*

**To Reproduce**
1.  Create a new subset.
2. Go to the "Publish" form step.
3.  Switch of the internet on the mashine.
4.  Click the "Save button".
5.  See the error "Failed to fetch" for metadata and "Sending version data to the server" message.

**Expected behavior**
Either do not show the "Sending version data to the server" message.
Or make the app show failed version saving attempt.

**Suggested solution**
To not show the "Sending version data to the server" message is ore natural. Probably Message, in that case, has to be "Cannot save the version before the metadata is successfully saved".
FYI: If the metadata saving process filed, the application does not attempt to send the version to the server.

**Comment by gbudjeakp** [comment]
Hello I was wondering if this issue is open for contribution? if so I would love to work on this.
