### ISSUE TITLE
Date Picker lib

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#42]
**Describe the bug**
It is possible to type 001 in day or month fied. Unaccepteble!
Date formate have to be DD.MM.YYYY everywere in the app.

**To Reproduce**
1. Go to "Create a subset" -> "Metadata".
2.  type '001' in the day input manually in the "Valid from" or "Valid to" field.
3. When focus of the day is still 001.

**Expected behavior**
Only valid days and months are allowed in the date picker.

**Solution suggestion**
Use another date picker library or use input type='date' as earlier:
![image](https://user-images.githubusercontent.com/21969896/80097787-2a3fae00-856c-11ea-8138-9bebe086fef7.png)

When it's done returnOffsetDate() from '../utils/strings' should be unnecessary. The date shoul be takan in correct time zone by default (it worked with input type='data').
![image](https://user-images.githubusercontent.com/21969896/80098081-94585300-856c-11ea-8e20-b43fe169dd70.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - haven't check

**Comment by grenben** [comment]
Since date pickers input field component is not exposed I think the best solution would be to replace this with a calendar that exposes the input and the write a mask for input field.

**Comment by drageset** [comment]
@alina-lapina is suggesting to revert to a previous version, where input type="date" was used. Why was this solution abandoned in favor of the current solution?

**Comment by alina-lapina** [comment]
It was difiicult to style,  📆  @drageset
But we prioritize functionality and security in such cases.
