### ISSUE TITLE
Code reordering: info text for rank column

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#52]
**Requirement**
Button / tooltip for rank column header with guide text about the rank number function.

> Tekst for tooltip: «Rekkefølgen på elementer kan endres ved å markere element (er) som skal flyttes (bruk Shift/Control hvis flere etterfølgende elementer skal flyttes samtidig), og «dra» dem til riktig posisjon (drag and drop).»

**Describe the solution you'd like**
1. Exact text ask @klassisk20
2. Use same tooltip component as other places in the code.

**Dependencies"
WCAG compliant tooltip #70 has to be implemented first.

**Describe alternatives you've considered**
Button / tooltip / accordeon

**Comment by grenben** [comment]
I`m not sure how to reach @klassisk20. Can one do that through Github? (How not used Github as a collaborating tool that much before)

**Comment by alina-lapina** [comment]
@grenben I've got the text, but we have to adjust it. And translate, I suppose :)
I'll put in in the issue description.

**Comment by alina-lapina** [comment]
the thing is that a user does not to press shift, as you know,  @grenben, just klick on the rows.

**Comment by grenben** [comment]
Shift?  I haven't heard anything regarding using shift. Why should one press shift?

**Comment by grenben** [comment]
Since SSB does not (?) have a proper tooltip to use I think we´ll have to implement one that will work with Wcag. I have a feeling that accessibility is going to be a issue later on...?

**Comment by alina-lapina** [comment]
Excellent! If you want you can fork and pull request your tooltip branch directly to statisticsnorway
/design-system (i'll register an issue). You can than use SSB's storybook. If you dont want, feel free to implement it directly in klass-subsets-client, og course! Love the initiative ;)

**Comment by alina-lapina** [comment]
Excellent! If you want you can fork and pull request your tooltip branch directly to statisticsnorway
/design-system (i'll register an issue). You can than use SSB's storybook. If you dont want, feel free to implement it directly in klass-subsets-client, og course! Love the initiative ;)
________________________________

**Comment by grenben** [comment]
I was thinking more about implementing a library of some sort.
I did not see you comments until now. Tooltip is implemented. I did add the required aria attributes for tooltip. The only thing missing is ESC keypress disposal of a tooltip.
I think we should down prioritize the #70 issue and move ahead to get the app in better shape.
That's however not my decision... :)

**Comment by alina-lapina** [comment]
Sorry, I wasn't following. I did not knew which issue you was workin on. Please, @grenben tag me on comments you waiting for my response to. I do agree to prioritize #70 (I even marked this issue as dependent on #70). 

Anyway, I have approved and merged https://github.com/statisticsnorway/klass-subsets-client/pull/75. 

It looks different from the other tooltip on the page. Will you fix it?
![image](https://user-images.githubusercontent.com/21969896/79975353-2132dc00-849b-11ea-9028-4bdfa26eef56.png)
