### ISSUE TITLE
Skip parentheses in search field 

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#53]
**Describe the bug**
When a classification with parentheses in the name property is chosen by mouse click in a search field, search fails.

**To Reproduce**
1. "Create a subset" -> "Search codes"
2. In the search field type 'nær'
3. When alternatives are shown, select "Standard for næringsgruppering (SN)", press ENTER.
4. No classifications found. It's wrong. There has to be one.
5. Place cursor in the input field and remove text from the end to the first parenthese include.
6. Press ENTER again.
7. The correct search serult is present: Standard for næringsgruppering (SN).

**Expected behavior**
1. Search fields has to ignor unaxeptable text, and respose with correct result.
2. Any restrictions have to be text message about in the GUI.

**Suggested solution**
0. When clicked on the suggestion the search results have to appear immeditely, without extra ENTER press.
1. Filter text in the inputs automaticalluy
2. Tooltip about spec chars

**Comment by grenben** [comment]
App also crashes if we remove one of the parentheses in search field. "SubsetCodes.jsx:57 Uncaught SyntaxError: Invalid regular expression: /standard for næringsgruppering (sn/: Unterminated group"
