### ISSUE TITLE
Code reordering: input type number arrows 

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#56]
**Requirement**
Arrows in style of input type=number on the "Reorder" step of the subsets form have to be invisible for users. (list.jsx, line 48:  <input type='number' name='rank').
Arrows  - small buttons 'up' and 'down' is shown when the input has forcus on.

**Solution**
Correct the CSS style for input type=number fields.
Do not change the input type to text -- we don't want to loose build-in validation and restrictions.

**Describe alternatives you've considered**
Make the arrows work for user - move the item up or down in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/21969896/79962022-ccd23100-8487-11ea-8818-42879b01eeed.png)

**Comment by grenben** [comment]
Could you elaborate on what this issue is about?

**Comment by grenben** [comment]
Done.

**Comment by alina-lapina** [comment]
@grenben 
I still can see the arrows in version v0.2.4 :( 
I move the issue to backlog for now and **prioritize it down**.

**Comment by alina-lapina** [comment]
https://stackoverflow.com/questions/26024771/styling-a-input-type-number/26024834#26024834
