### ISSUE TITLE
Date is one day before

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#69]
**Describe the bug**
The date does not the same on the next form step and Review.
Date formate have to be DD.MM.YYYY everywere in the app.

**To Reproduce**
1. Go to "Create a subset" -> "Metadata".
2. Choose a date in the "Valid from" or "Valid to" field.
3. Go to "Create a subset" -> "Choose code" or "Create a subset" -> "Review and publish".
4. Check out the dates in the validity period text: the dates are different from the chosen one.

**Expected behavior**
Same date as picked in date picker is used for search and stored in the subset.

**Solution suggestion**
Choose correct date convertion function to string. 
OR 
implement date picker which picks in local time, see #42 solution suggestion.

**Comment by grenben** [comment]
I had to do this in order to solve issue #57.
