### ISSUE TITLE
It takes too long to expand codes for Standard for næringsgruppering (SN)

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#78]
Dublicat, see #71 

**Describe the bug**
It takes to slow to expand codes (click the check box besides code) which includes notes and hava thousands of codes.

**To Reproduce**
1. Go to 'Metadata'
2. Pick a valid from date
3. Go to 'Choose classifications and code lists'
4. Serach for 'nær'
5. Expand codes for Standard for næringsgruppering (SN).
6. it takes over 1 sec to expand

**Expected behavior**
Show available data fast at once it received, update when new data becomes available.

**Suggested solution**
Start notes fetching later, whed codes are expanded.

**Comment by grenben** [comment]
This should be paginated with SSB pagination component?
