### ISSUE TITLE
Focus on the top

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#83]
**Describe the bug**
meld inn av @klassisk20
når jeg velger "Velg kodeverk", og den tilhørende sida dukker opp, så kommer vi inn "nedenfra" og får med så mye av SSB-informasjonen, at vi må scrolle for å kunne se valgt gyldighetsperiode, og kunne søke etter kodeverk. I forrige versjon kom vi inn fra toppen av sida, da kunne vi se gyldighetsperiode og søke etter kodeverk direkte, og ssb-informasjonen nederst på sida, viste ikke.

**To Reproduce**
1. Go to 'Metadata'
2. Click Next button to go to 'Chose classifications'
3. Focus is on the footer!
(havent reproduced by myself)

**Expected behavior**
Focus has to be on top of the form steps. 
On the 'Choose classification' step, the focus could be in the search input?

**Aditionl context:**
ref to my personal slack chat med @klassisk20: https://ssb-norge.slack.com/archives/C42H3BL5N/p1587710609146000?thread_ts=1587646650.141800&cid=C42H3BL5N

**Comment by grenben** [comment]
The easiest solution for this problem is to scroll top this on mount?

**Comment by grenben** [comment]
This issue is due to the fact that the page height is subject to change when routing between pages. The focus should probably describe the route change?

**Comment by drageset** [comment]
> 
> 
> The easiest solution for this problem is to scroll top this on mount?

Sounds right. Or scroll to top on button clicked. This will fix the issue as described by user.
