### ISSUE TITLE
Form styling: input height

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-client#97]
**Describe the bug**
![image](https://user-images.githubusercontent.com/21969896/80740661-b297f300-8b18-11ea-9578-7f8045be6550.png)

**Additional context**
Use branch #95 
https://github.com/statisticsnorway/klass-subsets-client/pull/95

**Comment by grenben** [comment]
Tagge meg i disse så setter jeg opp det her i henhold til style guiden plus input fra deg.
